# Generated by Django 5.2.4 on 2025-07-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
