# Generated by Django 5.2.4 on 2025-07-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0002_remove_cart_products_alter_cart_user_and_more'),
        ('product_app', '0004_alter_product_category_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
